#!/bin/bash
# =============================================================================
# deploy-node-setup.sh
# Run from WSL to configure all cluster nodes after a rebuild.
#
# What it does:
#   1. Copies scripts to each node
#   2. Runs configure-containerd.sh (transfer plugin fix + nfs-common)
#   3. Runs install-registry-ca.sh (system trust store + hosts.toml)
#
# Prerequisites:
#   - CA cert at /tmp/registry-tls/ca.crt (generated by scripts/generate-registry-tls.sh)
#   - SSH access to all nodes as pdawson
#
# Usage:
#   ./scripts/node-setup/deploy-node-setup.sh
#   ./scripts/node-setup/deploy-node-setup.sh 192.168.100.11  # single node
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CA_CERT="/tmp/registry-tls/ca.crt"
NODES=("192.168.100.10" "192.168.100.11" "192.168.100.12")

if [ $# -gt 0 ]; then
  NODES=("$@")
fi

if [ ! -f "$CA_CERT" ]; then
  echo "ERROR: Registry CA cert not found at $CA_CERT"
  echo "Run: scripts/generate-registry-tls.sh  (or recover from K8s secret)"
  exit 1
fi

echo "Configuring nodes: ${NODES[*]}"
echo ""

for node in "${NODES[@]}"; do
  echo "=== $node ==="

  # Copy scripts and CA cert
  scp "$SCRIPT_DIR/configure-containerd.sh" pdawson@$node:/tmp/configure-containerd.sh
  scp "$SCRIPT_DIR/install-registry-ca.sh"  pdawson@$node:/tmp/install-registry-ca.sh
  scp "$CA_CERT"                             pdawson@$node:/tmp/registry-ca.crt

  # Run with sudo (requires interactive password)
  ssh -t pdawson@$node "sudo bash /tmp/configure-containerd.sh && sudo bash /tmp/install-registry-ca.sh"
  echo ""
done

echo "All nodes configured. Verify with:"
echo "  kubectl get nodes"
echo "  kubectl run test --image=192.168.100.11:30500/claude-agent:latest --restart=Never --command -- echo ok"
