#!/bin/bash
# =============================================================================
# entrypoint.sh
# Main agent entrypoint. Runs inside every agent container.
#
# Flow:
#   1. Validate AGENT_ROLE, TASK_ID, and auth (API key or Claude.ai credentials)
#   2. Set MEMORY_BASE = /memory/tasks/$TASK_ID (task-scoped subdirectory)
#   3. Find the trigger payload (inbox for architect, queue for others)
#   4. Build a prompt: role identity + task memory base + payload + project context
#   5. Run Claude Code — it reads /agent/CLAUDE.md automatically from WORKDIR
#   6. Exit with Claude Code's exit code
#
# Role-specific behaviour and project conventions come from:
#   /agent/CLAUDE.md          — baked into image, read automatically by Claude Code
#   /memory/CLAUDE.md         — written by architect or user, included in prompt if present
#   /memory/tasks/$TASK_ID/workspace/<proj>/CLAUDE.md — project conventions
# =============================================================================

set -euo pipefail

# ── Helpers ──────────────────────────────────────────────────────────────────

log() {
  echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [$AGENT_ROLE] $*"
}

die() {
  log "ERROR: $*"
  exit 1
}

# ── Validate environment ──────────────────────────────────────────────────────

[ -z "${AGENT_ROLE:-}" ] && die "AGENT_ROLE is not set"

TASK_ID="${TASK_ID:-}"
[ -z "$TASK_ID" ] && die "TASK_ID is not set"

MEMORY_PATH="${MEMORY_PATH:-/memory}"
MEMORY_BASE="${MEMORY_PATH}/tasks/${TASK_ID}"
AGENT_TIMEOUT="${AGENT_TIMEOUT:-300}"
AGENT_MAX_TURNS="${AGENT_MAX_TURNS:-10}"

log "Starting agent role=$AGENT_ROLE task=$TASK_ID timeout=${AGENT_TIMEOUT}s max-turns=${AGENT_MAX_TURNS}"

# ── Auth: API key or Claude.ai credentials ───────────────────────────────────

CREDS_MOUNT="${HOME:-/home/agent}/.claude-creds/.credentials.json"
if [ -z "${ANTHROPIC_API_KEY:-}" ]; then
  if [ -f "$CREDS_MOUNT" ]; then
    mkdir -p "${HOME:-/home/agent}/.claude"
    cp "$CREDS_MOUNT" "${HOME:-/home/agent}/.claude/.credentials.json"
    log "Using Claude.ai credentials from mounted secret"
  else
    die "Neither ANTHROPIC_API_KEY nor claude-credentials secret is configured"
  fi
fi

# ── Ensure task-scoped memory directories exist ───────────────────────────────

mkdir -p \
  "${MEMORY_BASE}/inbox" \
  "${MEMORY_BASE}/specs" \
  "${MEMORY_BASE}/queue" \
  "${MEMORY_BASE}/queue/active" \
  "${MEMORY_BASE}/workspace" \
  "${MEMORY_BASE}/reviews" \
  "${MEMORY_BASE}/deployments" \
  "${MEMORY_BASE}/logs"

# ── Find the trigger payload ──────────────────────────────────────────────────
# Architect reads from MEMORY_BASE/inbox/ (written by the dispatcher)
# All other agents read from MEMORY_BASE/queue/<role>.json (written by previous agent)

PAYLOAD_FILE=""

if [ "$AGENT_ROLE" = "architect" ]; then
  PAYLOAD_FILE=$(ls -t "${MEMORY_BASE}/inbox/"*.json 2>/dev/null | head -1 || true)
  [ -z "$PAYLOAD_FILE" ] && die "No payload found in ${MEMORY_BASE}/inbox/"
else
  PAYLOAD_FILE="${MEMORY_BASE}/queue/${AGENT_ROLE}.json"
  if [ ! -f "$PAYLOAD_FILE" ]; then
    # Queue-watcher moves the trigger to queue/active/ before dispatching the
    # event so the file survives pod scheduling and image pull delays.
    PAYLOAD_FILE="${MEMORY_BASE}/queue/active/${AGENT_ROLE}.json"
    [ -f "$PAYLOAD_FILE" ] || die "No trigger file found at queue/${AGENT_ROLE}.json or queue/active/${AGENT_ROLE}.json"
    log "Reading trigger from active/: $PAYLOAD_FILE"
  fi
fi

log "Reading payload from: $PAYLOAD_FILE"
PAYLOAD=$(cat "$PAYLOAD_FILE")

# ── Mock mode ─────────────────────────────────────────────────────────────────
# When AGENT_MOCK=true the Claude invocation is skipped entirely. Each role
# writes pre-canned fixture files and the appropriate trigger, exercising the
# full infrastructure chain (dispatch → job creation → NFS I/O → queue-watcher
# → chaining) at zero token cost.

if [ "${AGENT_MOCK:-false}" = "true" ]; then
  log "MOCK MODE — writing fixture output, skipping Claude"
  TS=$(date -u +%Y%m%dT%H%M%S)
  TASK=$(echo "$PAYLOAD" | jq -r '.title // .event // "mock task"' 2>/dev/null || echo "mock task")

  case "$AGENT_ROLE" in
    architect)
      cat > "${MEMORY_BASE}/specs/mock-spec-${TS}.md" << EOF
# Mock Spec: ${TASK}
Generated by architect (mock) at ${TS}.

## Component: mock-service
- Endpoint: GET /mock → {"status":"ok"}
- Implementation: single Python file
EOF
      printf '{"from":"architect","task":"%s","output":"%s/specs/mock-spec-%s.md","notes":"mock run"}\n' \
        "$TASK" "$MEMORY_BASE" "$TS" > "${MEMORY_BASE}/queue/coder.json"
      ;;
    coder)
      mkdir -p "${MEMORY_BASE}/workspace/mock-project"
      cat > "${MEMORY_BASE}/workspace/mock-project/main.py" << 'EOF'
def hello():
    return {"status": "ok"}
EOF
      printf '{"from":"coder","task":"mock implementation","output":"%s/workspace/mock-project","notes":"mock run"}\n' \
        "$MEMORY_BASE" > "${MEMORY_BASE}/queue/tester.json"
      ;;
    tester)
      mkdir -p "${MEMORY_BASE}/workspace/mock-project"
      cat > "${MEMORY_BASE}/workspace/mock-project/test_main.py" << 'EOF'
from main import hello

def test_hello():
    assert hello() == {"status": "ok"}
EOF
      printf '{"from":"tester","task":"mock tests","output":"%s/workspace/mock-project/test_main.py","notes":"mock run"}\n' \
        "$MEMORY_BASE" > "${MEMORY_BASE}/queue/reviewer.json"
      ;;
    reviewer)
      cat > "${MEMORY_BASE}/reviews/mock-review-${TS}.md" << EOF
# Mock Review — ${TS}
Status: APPROVED
No issues found. Smoke test passed review stage.
EOF
      printf '{"from":"reviewer","task":"mock review","output":"%s/reviews/mock-review-%s.md","notes":"mock run — approved"}\n' \
        "$MEMORY_BASE" "$TS" > "${MEMORY_BASE}/queue/ops.json"
      ;;
    ops)
      mkdir -p "${MEMORY_BASE}/deployments/mock-${TS}"
      cat > "${MEMORY_BASE}/deployments/mock-${TS}/deployment.md" << EOF
# Mock Deployment — ${TS}
Status: SUCCESS
Full pipeline smoke test completed at ${TS}.
Chain: architect → coder → tester → reviewer → ops — all succeeded.
EOF
      ;;
    *)
      log "Unknown role in mock mode: $AGENT_ROLE — no fixture written"
      ;;
  esac

  cat > "${MEMORY_BASE}/logs/${AGENT_ROLE}-mock-${TS}.md" << EOF
# ${AGENT_ROLE} mock run — ${TS}
Task: ${TASK}
Result: Fixture written, trigger sent (if applicable).
EOF

  log "Mock run complete"
  exit 0
fi

# ── Build the prompt ──────────────────────────────────────────────────────────

# Global project context lives at /memory/CLAUDE.md (not task-scoped)
PROJECT_CONTEXT_CONTENT=""
if [ -f "${MEMORY_PATH}/CLAUDE.md" ]; then
  PROJECT_CONTEXT_CONTENT=$(cat "${MEMORY_PATH}/CLAUDE.md")
  log "Including project context from ${MEMORY_PATH}/CLAUDE.md"
fi

PROMPT=$(cat << PROMPTEOF
# Your Role
You are the **${AGENT_ROLE}** agent.

# Task Memory Base
Your task-scoped memory directory is: **${MEMORY_BASE}**
Use this as the root for all reads and writes in this pipeline run.
Do not use flat /memory/ paths — this run is isolated under its own task subdirectory.

# Your Task
The following payload triggered your execution:

\`\`\`json
${PAYLOAD}
\`\`\`
${PROJECT_CONTEXT_CONTENT:+
# Project Context
${PROJECT_CONTEXT_CONTENT}
}
Begin your work now.
PROMPTEOF
)

# ── Run Claude Code ───────────────────────────────────────────────────────────
# Claude Code reads /agent/CLAUDE.md automatically (WORKDIR is /agent).
# That file contains memory layout, chaining rules, role descriptions,
# and security rules — no need to repeat them in the prompt.

log "Launching Claude Code..."

PROMPT_FILE=$(mktemp /tmp/agent-prompt-XXXXXX.md)
echo "$PROMPT" > "$PROMPT_FILE"

EXIT_CODE=0
timeout "${AGENT_TIMEOUT}" claude \
  --print \
  --max-turns "${AGENT_MAX_TURNS}" \
  --dangerously-skip-permissions \
  "$(cat "$PROMPT_FILE")" 2>&1 | tee "${MEMORY_BASE}/logs/${AGENT_ROLE}-output-$(date -u +%Y%m%dT%H%M%S).log" \
  || EXIT_CODE=$?

rm -f "$PROMPT_FILE"

# ── Handle completion ─────────────────────────────────────────────────────────

if [ $EXIT_CODE -eq 0 ]; then
  log "Completed successfully"
  if [ "$AGENT_ROLE" != "architect" ] && [ -f "$PAYLOAD_FILE" ]; then
    rm -f "$PAYLOAD_FILE" 2>/dev/null \
      && log "Consumed trigger file: $PAYLOAD_FILE" \
      || log "Warning: could not remove trigger file $PAYLOAD_FILE (NFS ownership — non-fatal)"
  fi
elif [ $EXIT_CODE -eq 124 ]; then
  die "Timed out after ${AGENT_TIMEOUT}s"
else
  die "Claude Code exited with code $EXIT_CODE"
fi

log "Agent $AGENT_ROLE finished"
exit 0
