FROM python:3.12-slim
ARG BUILD_DATE=unknown
LABEL build-date=$BUILD_DATE
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
